name: Starter Workflow

on: [workflow_dispatch]

jobs:
  call-generate:
    uses: kbakdev/reusable-workflows/.github/workflows/generate-output.yaml@main

  call-use:
    needs: call-generate
    uses: kbakdev/reusable-workflows/.github/workflows/use-output.yaml@main
    with:
      input: ${{ needs.call-generate.outputs.output }}
